### ISSUE TITLE
Potential incompatibility with RSpec 3.5.4

### ISSUE THREAD

**Issue by axelson** [brooklynDev/airborne#121]
I'm trying to upgrade from RSpec 3.2.0 with airborne 0.2.5 to RSpec 3.5.4 with airborne 0.2.7 but I get the following error when trying to run my tests:

```
$ bundle exec rspec
bundler: failed to load command: rspec (/Users/jason/.rbenv/versions/2.2.5/bin/rspec)
Bundler::GemRequireError: There was an error while trying to load the gem 'airborne'.
Gem Load Error is: undefined method `requester_module' for #<RSpec::Core::Configuration:0x007facbbb26ac8>
Backtrace for gem load error is:
/Users/jason/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/airborne-0.2.7/lib/airborne/base.rb:19:in `included'
/Users/jason/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:2070:in `include'
/Users/jason/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:2070:in `safe_include'
/Users/jason/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1236:in `block in include'
/Users/jason/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:2053:in `block (2 levels) in on_existing_matching_groups'
```

Is there something wrong with my setup or is there an incompatibility?

**Comment by axelson** [comment]
Any ideas on what to try?

**Comment by sethpollack** [comment]
What does your configuration look like?

**Comment by axelson** [comment]
Nothing too interesting as far as I can tell. I believe the problem is in Airborne. I just submitted the PR to fix it and you merged it already so I guess this should be good now.

**Comment by axelson** [comment]
Do you know when the next release will be cut?

**Comment by sethpollack** [comment]
I just pushed

**Comment by axelson** [comment]
Great. I see it now. Thanks for the help! ❤️

**Comment by sethpollack** [comment]
NP
