### ISSUE TITLE
Expecting array responses

### ISSUE THREAD

**Issue by namxam** [brooklynDev/airborne#85]
In 0.1.15 I had no issue with ```expect_json([])``` but now that I upgraded to 0.2.1 it throws an error:

```
Failure/Error: expect_json([])

NoMethodError:
 undefined method `keys' for []:Array
# /ruby-2.2.3/gems/airborne-0.2.1/lib/airborne/request_expectations.rb:83:in `expect_json_impl'
# /ruby-2.2.3/gems/airborne-0.2.1/lib/airborne/request_expectations.rb:19:in `block in expect_json'
# /ruby-2.2.3/gems/airborne-0.2.1/lib/airborne/request_expectations.rb:139:in `call_with_path'
# /ruby-2.2.3/gems/airborne-0.2.1/lib/airborne/request_expectations.rb:18:in `expect_json'
```

Is this expected?

**Comment by sethpollack** [comment]
Ok its updated and should work now.
